/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type PoolKeyStruct = {
  currency0: AddressLike;
  currency1: AddressLike;
  fee: BigNumberish;
  tickSpacing: BigNumberish;
  hooks: AddressLike;
};

export type PoolKeyStructOutput = [
  currency0: string,
  currency1: string,
  fee: bigint,
  tickSpacing: bigint,
  hooks: string
] & {
  currency0: string;
  currency1: string;
  fee: bigint;
  tickSpacing: bigint;
  hooks: string;
};

export type ModifyLiquidityParamsStruct = {
  tickLower: BigNumberish;
  tickUpper: BigNumberish;
  liquidityDelta: BigNumberish;
  salt: BytesLike;
};

export type ModifyLiquidityParamsStructOutput = [
  tickLower: bigint,
  tickUpper: bigint,
  liquidityDelta: bigint,
  salt: string
] & {
  tickLower: bigint;
  tickUpper: bigint;
  liquidityDelta: bigint;
  salt: string;
};

export type SwapParamsStruct = {
  zeroForOne: boolean;
  amountSpecified: BigNumberish;
  sqrtPriceLimitX96: BigNumberish;
};

export type SwapParamsStructOutput = [
  zeroForOne: boolean,
  amountSpecified: bigint,
  sqrtPriceLimitX96: bigint
] & { zeroForOne: boolean; amountSpecified: bigint; sqrtPriceLimitX96: bigint };

export declare namespace AntiRugHook {
  export type VestingConfigStruct = {
    founder: AddressLike;
    founderToken: AddressLike;
    lockStartTime: BigNumberish;
    cliffDuration: BigNumberish;
    vestingDuration: BigNumberish;
    totalLocked: BigNumberish;
    released: BigNumberish;
    initialized: boolean;
  };

  export type VestingConfigStructOutput = [
    founder: string,
    founderToken: string,
    lockStartTime: bigint,
    cliffDuration: bigint,
    vestingDuration: bigint,
    totalLocked: bigint,
    released: bigint,
    initialized: boolean
  ] & {
    founder: string;
    founderToken: string;
    lockStartTime: bigint;
    cliffDuration: bigint;
    vestingDuration: bigint;
    totalLocked: bigint;
    released: bigint;
    initialized: boolean;
  };
}

export declare namespace Hooks {
  export type PermissionsStruct = {
    beforeInitialize: boolean;
    afterInitialize: boolean;
    beforeAddLiquidity: boolean;
    afterAddLiquidity: boolean;
    beforeRemoveLiquidity: boolean;
    afterRemoveLiquidity: boolean;
    beforeSwap: boolean;
    afterSwap: boolean;
    beforeDonate: boolean;
    afterDonate: boolean;
    beforeSwapReturnDelta: boolean;
    afterSwapReturnDelta: boolean;
    afterAddLiquidityReturnDelta: boolean;
    afterRemoveLiquidityReturnDelta: boolean;
  };

  export type PermissionsStructOutput = [
    beforeInitialize: boolean,
    afterInitialize: boolean,
    beforeAddLiquidity: boolean,
    afterAddLiquidity: boolean,
    beforeRemoveLiquidity: boolean,
    afterRemoveLiquidity: boolean,
    beforeSwap: boolean,
    afterSwap: boolean,
    beforeDonate: boolean,
    afterDonate: boolean,
    beforeSwapReturnDelta: boolean,
    afterSwapReturnDelta: boolean,
    afterAddLiquidityReturnDelta: boolean,
    afterRemoveLiquidityReturnDelta: boolean
  ] & {
    beforeInitialize: boolean;
    afterInitialize: boolean;
    beforeAddLiquidity: boolean;
    afterAddLiquidity: boolean;
    beforeRemoveLiquidity: boolean;
    afterRemoveLiquidity: boolean;
    beforeSwap: boolean;
    afterSwap: boolean;
    beforeDonate: boolean;
    afterDonate: boolean;
    beforeSwapReturnDelta: boolean;
    afterSwapReturnDelta: boolean;
    afterAddLiquidityReturnDelta: boolean;
    afterRemoveLiquidityReturnDelta: boolean;
  };
}

export interface AntiRugHookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "afterAddLiquidity"
      | "afterDonate"
      | "afterInitialize"
      | "afterRemoveLiquidity"
      | "afterSwap"
      | "beforeAddLiquidity"
      | "beforeDonate"
      | "beforeInitialize"
      | "beforeRemoveLiquidity"
      | "beforeSwap"
      | "calculateVestedAmount"
      | "getHookPermissions"
      | "getVestingStatus"
      | "initializeVesting"
      | "owner"
      | "poolManager"
      | "transferOwnership"
      | "vestingConfigs"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FounderSellBlocked"
      | "OwnershipTransferred"
      | "TokensReleased"
      | "VestingInitialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "afterAddLiquidity",
    values: [
      AddressLike,
      PoolKeyStruct,
      ModifyLiquidityParamsStruct,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterDonate",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "afterInitialize",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "afterRemoveLiquidity",
    values: [
      AddressLike,
      PoolKeyStruct,
      ModifyLiquidityParamsStruct,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "afterSwap",
    values: [
      AddressLike,
      PoolKeyStruct,
      SwapParamsStruct,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeAddLiquidity",
    values: [AddressLike, PoolKeyStruct, ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeDonate",
    values: [AddressLike, PoolKeyStruct, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeInitialize",
    values: [AddressLike, PoolKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeRemoveLiquidity",
    values: [AddressLike, PoolKeyStruct, ModifyLiquidityParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeSwap",
    values: [AddressLike, PoolKeyStruct, SwapParamsStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateVestedAmount",
    values: [AntiRugHook.VestingConfigStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHookPermissions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingStatus",
    values: [PoolKeyStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeVesting",
    values: [
      PoolKeyStruct,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "poolManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingConfigs",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "afterAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterDonate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "afterRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "afterSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beforeAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeDonate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeInitialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeRemoveLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "beforeSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateVestedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHookPermissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "poolManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingConfigs",
    data: BytesLike
  ): Result;
}

export namespace FounderSellBlockedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    founder: AddressLike,
    attemptedAmount: BigNumberish,
    timeRemaining: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    founder: string,
    attemptedAmount: bigint,
    timeRemaining: bigint
  ];
  export interface OutputObject {
    poolId: string;
    founder: string;
    attemptedAmount: bigint;
    timeRemaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    founder: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, founder: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    founder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingInitializedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    founder: AddressLike,
    cliffDuration: BigNumberish,
    vestingDuration: BigNumberish,
    totalLocked: BigNumberish
  ];
  export type OutputTuple = [
    poolId: string,
    founder: string,
    cliffDuration: bigint,
    vestingDuration: bigint,
    totalLocked: bigint
  ];
  export interface OutputObject {
    poolId: string;
    founder: string;
    cliffDuration: bigint;
    vestingDuration: bigint;
    totalLocked: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AntiRugHook extends BaseContract {
  connect(runner?: ContractRunner | null): AntiRugHook;
  waitForDeployment(): Promise<this>;

  interface: AntiRugHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  afterAddLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      delta: BigNumberish,
      feesAccrued: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  afterDonate: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  afterInitialize: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      tick: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  afterRemoveLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      delta: BigNumberish,
      feesAccrued: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  afterSwap: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: SwapParamsStruct,
      delta: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;

  beforeAddLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeDonate: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeInitialize: TypedContractMethod<
    [sender: AddressLike, key: PoolKeyStruct, sqrtPriceX96: BigNumberish],
    [string],
    "nonpayable"
  >;

  beforeRemoveLiquidity: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  beforeSwap: TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: SwapParamsStruct,
      hookData: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;

  calculateVestedAmount: TypedContractMethod<
    [config: AntiRugHook.VestingConfigStruct, timeElapsed: BigNumberish],
    [bigint],
    "view"
  >;

  getHookPermissions: TypedContractMethod<
    [],
    [Hooks.PermissionsStructOutput],
    "view"
  >;

  getVestingStatus: TypedContractMethod<
    [key: PoolKeyStruct],
    [
      [boolean, string, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        founder: string;
        totalLocked: bigint;
        vested: bigint;
        released: bigint;
        available: bigint;
        timeUntilFullyVested: bigint;
      }
    ],
    "view"
  >;

  initializeVesting: TypedContractMethod<
    [
      key: PoolKeyStruct,
      founder: AddressLike,
      founderToken: AddressLike,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      totalLocked: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  poolManager: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vestingConfigs: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        founder: string;
        founderToken: string;
        lockStartTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        totalLocked: bigint;
        released: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "afterAddLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      delta: BigNumberish,
      feesAccrued: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterDonate"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterInitialize"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      sqrtPriceX96: BigNumberish,
      tick: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterRemoveLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      delta: BigNumberish,
      feesAccrued: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "afterSwap"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: SwapParamsStruct,
      delta: BigNumberish,
      hookData: BytesLike
    ],
    [[string, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeAddLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeDonate"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      amount0: BigNumberish,
      amount1: BigNumberish,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeInitialize"
  ): TypedContractMethod<
    [sender: AddressLike, key: PoolKeyStruct, sqrtPriceX96: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeRemoveLiquidity"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: ModifyLiquidityParamsStruct,
      hookData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeSwap"
  ): TypedContractMethod<
    [
      sender: AddressLike,
      key: PoolKeyStruct,
      params: SwapParamsStruct,
      hookData: BytesLike
    ],
    [[string, bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateVestedAmount"
  ): TypedContractMethod<
    [config: AntiRugHook.VestingConfigStruct, timeElapsed: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHookPermissions"
  ): TypedContractMethod<[], [Hooks.PermissionsStructOutput], "view">;
  getFunction(
    nameOrSignature: "getVestingStatus"
  ): TypedContractMethod<
    [key: PoolKeyStruct],
    [
      [boolean, string, bigint, bigint, bigint, bigint, bigint] & {
        initialized: boolean;
        founder: string;
        totalLocked: bigint;
        vested: bigint;
        released: bigint;
        available: bigint;
        timeUntilFullyVested: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initializeVesting"
  ): TypedContractMethod<
    [
      key: PoolKeyStruct,
      founder: AddressLike,
      founderToken: AddressLike,
      cliffDuration: BigNumberish,
      vestingDuration: BigNumberish,
      totalLocked: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poolManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingConfigs"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        founder: string;
        founderToken: string;
        lockStartTime: bigint;
        cliffDuration: bigint;
        vestingDuration: bigint;
        totalLocked: bigint;
        released: bigint;
        initialized: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "FounderSellBlocked"
  ): TypedContractEvent<
    FounderSellBlockedEvent.InputTuple,
    FounderSellBlockedEvent.OutputTuple,
    FounderSellBlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VestingInitialized"
  ): TypedContractEvent<
    VestingInitializedEvent.InputTuple,
    VestingInitializedEvent.OutputTuple,
    VestingInitializedEvent.OutputObject
  >;

  filters: {
    "FounderSellBlocked(bytes32,address,uint256,uint256)": TypedContractEvent<
      FounderSellBlockedEvent.InputTuple,
      FounderSellBlockedEvent.OutputTuple,
      FounderSellBlockedEvent.OutputObject
    >;
    FounderSellBlocked: TypedContractEvent<
      FounderSellBlockedEvent.InputTuple,
      FounderSellBlockedEvent.OutputTuple,
      FounderSellBlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokensReleased(bytes32,address,uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;

    "VestingInitialized(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      VestingInitializedEvent.InputTuple,
      VestingInitializedEvent.OutputTuple,
      VestingInitializedEvent.OutputObject
    >;
    VestingInitialized: TypedContractEvent<
      VestingInitializedEvent.InputTuple,
      VestingInitializedEvent.OutputTuple,
      VestingInitializedEvent.OutputObject
    >;
  };
}
