/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BuybackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "consulToken"
      | "depositUsdc"
      | "dexRouter"
      | "emergencyWithdraw"
      | "executeBuyback"
      | "getBuybackStats"
      | "hubDao"
      | "owner"
      | "renounceOwnership"
      | "setDexRouter"
      | "setHubDao"
      | "totalBurned"
      | "totalBuybackSpent"
      | "transferOwnership"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BuybackExecuted"
      | "DexRouterUpdated"
      | "HubDaoUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consulToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositUsdc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dexRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBuyback",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuybackStats",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "hubDao", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDexRouter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHubDao",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBurned",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalBuybackSpent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "consulToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dexRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBuyback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuybackStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hubDao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDexRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setHubDao", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBurned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBuybackSpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace BuybackExecutedEvent {
  export type InputTuple = [
    usdcSpent: BigNumberish,
    consulBought: BigNumberish,
    consulBurned: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    usdcSpent: bigint,
    consulBought: bigint,
    consulBurned: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    usdcSpent: bigint;
    consulBought: bigint;
    consulBurned: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DexRouterUpdatedEvent {
  export type InputTuple = [oldRouter: AddressLike, newRouter: AddressLike];
  export type OutputTuple = [oldRouter: string, newRouter: string];
  export interface OutputObject {
    oldRouter: string;
    newRouter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HubDaoUpdatedEvent {
  export type InputTuple = [oldHubDao: AddressLike, newHubDao: AddressLike];
  export type OutputTuple = [oldHubDao: string, newHubDao: string];
  export interface OutputObject {
    oldHubDao: string;
    newHubDao: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Buyback extends BaseContract {
  connect(runner?: ContractRunner | null): Buyback;
  waitForDeployment(): Promise<this>;

  interface: BuybackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consulToken: TypedContractMethod<[], [string], "view">;

  depositUsdc: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  dexRouter: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeBuyback: TypedContractMethod<
    [usdcAmount: BigNumberish, minConsulOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBuybackStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        usdcSpent: bigint;
        consulBurned: bigint;
        usdcBalance: bigint;
      }
    ],
    "view"
  >;

  hubDao: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDexRouter: TypedContractMethod<
    [_dexRouter: AddressLike],
    [void],
    "nonpayable"
  >;

  setHubDao: TypedContractMethod<[_hubDao: AddressLike], [void], "nonpayable">;

  totalBurned: TypedContractMethod<[], [bigint], "view">;

  totalBuybackSpent: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consulToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "depositUsdc"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dexRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBuyback"
  ): TypedContractMethod<
    [usdcAmount: BigNumberish, minConsulOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuybackStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        usdcSpent: bigint;
        consulBurned: bigint;
        usdcBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hubDao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDexRouter"
  ): TypedContractMethod<[_dexRouter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHubDao"
  ): TypedContractMethod<[_hubDao: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalBurned"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBuybackSpent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BuybackExecuted"
  ): TypedContractEvent<
    BuybackExecutedEvent.InputTuple,
    BuybackExecutedEvent.OutputTuple,
    BuybackExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DexRouterUpdated"
  ): TypedContractEvent<
    DexRouterUpdatedEvent.InputTuple,
    DexRouterUpdatedEvent.OutputTuple,
    DexRouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HubDaoUpdated"
  ): TypedContractEvent<
    HubDaoUpdatedEvent.InputTuple,
    HubDaoUpdatedEvent.OutputTuple,
    HubDaoUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BuybackExecuted(uint256,uint256,uint256,uint256)": TypedContractEvent<
      BuybackExecutedEvent.InputTuple,
      BuybackExecutedEvent.OutputTuple,
      BuybackExecutedEvent.OutputObject
    >;
    BuybackExecuted: TypedContractEvent<
      BuybackExecutedEvent.InputTuple,
      BuybackExecutedEvent.OutputTuple,
      BuybackExecutedEvent.OutputObject
    >;

    "DexRouterUpdated(address,address)": TypedContractEvent<
      DexRouterUpdatedEvent.InputTuple,
      DexRouterUpdatedEvent.OutputTuple,
      DexRouterUpdatedEvent.OutputObject
    >;
    DexRouterUpdated: TypedContractEvent<
      DexRouterUpdatedEvent.InputTuple,
      DexRouterUpdatedEvent.OutputTuple,
      DexRouterUpdatedEvent.OutputObject
    >;

    "HubDaoUpdated(address,address)": TypedContractEvent<
      HubDaoUpdatedEvent.InputTuple,
      HubDaoUpdatedEvent.OutputTuple,
      HubDaoUpdatedEvent.OutputObject
    >;
    HubDaoUpdated: TypedContractEvent<
      HubDaoUpdatedEvent.InputTuple,
      HubDaoUpdatedEvent.OutputTuple,
      HubDaoUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
