/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as buybackSol from "./Buyback.sol";
export type { buybackSol };
import type * as hubDaoSol from "./HubDAO.sol";
export type { hubDaoSol };
import type * as test from "./test";
export type { test };
export type { AntiRugHook } from "./AntiRugHook";
export type { ConsulStaking } from "./ConsulStaking";
export type { ConsulToken } from "./ConsulToken";
export type { Fundraiser } from "./Fundraiser";
export type { ProjectRegistry } from "./ProjectRegistry";
export type { Squads } from "./Squads";
