/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProjectRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "founderProjects"
      | "getProject"
      | "getProjectsByFounder"
      | "isNameAvailable"
      | "projects"
      | "registerProject"
      | "totalProjects"
      | "transferProjectOwnership"
      | "updateManifest"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProjectRegistered"
      | "ProjectTransferred"
      | "ProjectUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "founderProjects",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getProject", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getProjectsByFounder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isNameAvailable",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "projects", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerProject",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProjects",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferProjectOwnership",
    values: [string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateManifest",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "founderProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProject", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getProjectsByFounder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isNameAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProjects",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProjectOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateManifest",
    data: BytesLike
  ): Result;
}

export namespace ProjectRegisteredEvent {
  export type InputTuple = [
    nameHash: string,
    name: string,
    founder: AddressLike,
    manifest: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nameHash: string,
    name: string,
    founder: string,
    manifest: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    nameHash: string;
    name: string;
    founder: string;
    manifest: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectTransferredEvent {
  export type InputTuple = [
    nameHash: string,
    name: string,
    oldFounder: AddressLike,
    newFounder: AddressLike
  ];
  export type OutputTuple = [
    nameHash: string,
    name: string,
    oldFounder: string,
    newFounder: string
  ];
  export interface OutputObject {
    nameHash: string;
    name: string;
    oldFounder: string;
    newFounder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectUpdatedEvent {
  export type InputTuple = [
    nameHash: string,
    name: string,
    manifest: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nameHash: string,
    name: string,
    manifest: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    nameHash: string;
    name: string;
    manifest: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProjectRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ProjectRegistry;
  waitForDeployment(): Promise<this>;

  interface: ProjectRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  founderProjects: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getProject: TypedContractMethod<
    [name: string],
    [
      [string, string, string, bigint, boolean] & {
        projectName: string;
        manifest: string;
        founder: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  getProjectsByFounder: TypedContractMethod<
    [founder: AddressLike],
    [string[]],
    "view"
  >;

  isNameAvailable: TypedContractMethod<[name: string], [boolean], "view">;

  projects: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        manifest: string;
        founder: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  registerProject: TypedContractMethod<
    [name: string, manifest: string],
    [void],
    "nonpayable"
  >;

  totalProjects: TypedContractMethod<[], [bigint], "view">;

  transferProjectOwnership: TypedContractMethod<
    [name: string, newFounder: AddressLike],
    [void],
    "nonpayable"
  >;

  updateManifest: TypedContractMethod<
    [name: string, manifest: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "founderProjects"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProject"
  ): TypedContractMethod<
    [name: string],
    [
      [string, string, string, bigint, boolean] & {
        projectName: string;
        manifest: string;
        founder: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProjectsByFounder"
  ): TypedContractMethod<[founder: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isNameAvailable"
  ): TypedContractMethod<[name: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, boolean] & {
        name: string;
        manifest: string;
        founder: string;
        registeredAt: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProject"
  ): TypedContractMethod<
    [name: string, manifest: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalProjects"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferProjectOwnership"
  ): TypedContractMethod<
    [name: string, newFounder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateManifest"
  ): TypedContractMethod<
    [name: string, manifest: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProjectRegistered"
  ): TypedContractEvent<
    ProjectRegisteredEvent.InputTuple,
    ProjectRegisteredEvent.OutputTuple,
    ProjectRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectTransferred"
  ): TypedContractEvent<
    ProjectTransferredEvent.InputTuple,
    ProjectTransferredEvent.OutputTuple,
    ProjectTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProjectUpdated"
  ): TypedContractEvent<
    ProjectUpdatedEvent.InputTuple,
    ProjectUpdatedEvent.OutputTuple,
    ProjectUpdatedEvent.OutputObject
  >;

  filters: {
    "ProjectRegistered(string,string,address,string,uint256)": TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;
    ProjectRegistered: TypedContractEvent<
      ProjectRegisteredEvent.InputTuple,
      ProjectRegisteredEvent.OutputTuple,
      ProjectRegisteredEvent.OutputObject
    >;

    "ProjectTransferred(string,string,address,address)": TypedContractEvent<
      ProjectTransferredEvent.InputTuple,
      ProjectTransferredEvent.OutputTuple,
      ProjectTransferredEvent.OutputObject
    >;
    ProjectTransferred: TypedContractEvent<
      ProjectTransferredEvent.InputTuple,
      ProjectTransferredEvent.OutputTuple,
      ProjectTransferredEvent.OutputObject
    >;

    "ProjectUpdated(string,string,string,uint256)": TypedContractEvent<
      ProjectUpdatedEvent.InputTuple,
      ProjectUpdatedEvent.OutputTuple,
      ProjectUpdatedEvent.OutputObject
    >;
    ProjectUpdated: TypedContractEvent<
      ProjectUpdatedEvent.InputTuple,
      ProjectUpdatedEvent.OutputTuple,
      ProjectUpdatedEvent.OutputObject
    >;
  };
}
