/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SquadsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addMember"
      | "assignTask"
      | "completeTask"
      | "createSquad"
      | "createTask"
      | "fundSquadBudget"
      | "getSquadName"
      | "hubDao"
      | "owner"
      | "removeMember"
      | "renounceOwnership"
      | "setHubDao"
      | "squadCount"
      | "squads"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetAllocated"
      | "MemberAdded"
      | "MemberRemoved"
      | "OwnershipTransferred"
      | "SquadCreated"
      | "TaskAssigned"
      | "TaskCompleted"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "assignTask",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createSquad",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundSquadBudget",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSquadName",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hubDao", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeMember",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setHubDao",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "squadCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "squads",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addMember", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "assignTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSquad",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundSquadBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSquadName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hubDao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setHubDao", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "squadCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "squads", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace BudgetAllocatedEvent {
  export type InputTuple = [squadId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [squadId: bigint, amount: bigint];
  export interface OutputObject {
    squadId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberAddedEvent {
  export type InputTuple = [squadId: BigNumberish, member: AddressLike];
  export type OutputTuple = [squadId: bigint, member: string];
  export interface OutputObject {
    squadId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemberRemovedEvent {
  export type InputTuple = [squadId: BigNumberish, member: AddressLike];
  export type OutputTuple = [squadId: bigint, member: string];
  export interface OutputObject {
    squadId: bigint;
    member: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SquadCreatedEvent {
  export type InputTuple = [
    squadId: BigNumberish,
    name: string,
    squadType: BigNumberish
  ];
  export type OutputTuple = [squadId: bigint, name: string, squadType: bigint];
  export interface OutputObject {
    squadId: bigint;
    name: string;
    squadType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskAssignedEvent {
  export type InputTuple = [
    squadId: BigNumberish,
    taskId: BigNumberish,
    assignee: AddressLike
  ];
  export type OutputTuple = [squadId: bigint, taskId: bigint, assignee: string];
  export interface OutputObject {
    squadId: bigint;
    taskId: bigint;
    assignee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [squadId: BigNumberish, taskId: BigNumberish];
  export type OutputTuple = [squadId: bigint, taskId: bigint];
  export interface OutputObject {
    squadId: bigint;
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    squadId: BigNumberish,
    taskId: BigNumberish,
    description: string,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    squadId: bigint,
    taskId: bigint,
    description: string,
    reward: bigint
  ];
  export interface OutputObject {
    squadId: bigint;
    taskId: bigint;
    description: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Squads extends BaseContract {
  connect(runner?: ContractRunner | null): Squads;
  waitForDeployment(): Promise<this>;

  interface: SquadsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addMember: TypedContractMethod<
    [squadId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;

  assignTask: TypedContractMethod<
    [squadId: BigNumberish, taskId: BigNumberish, assignee: AddressLike],
    [void],
    "nonpayable"
  >;

  completeTask: TypedContractMethod<
    [squadId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createSquad: TypedContractMethod<
    [name: string, squadType: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [squadId: BigNumberish, description: string, reward: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundSquadBudget: TypedContractMethod<
    [squadId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getSquadName: TypedContractMethod<[squadId: BigNumberish], [string], "view">;

  hubDao: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeMember: TypedContractMethod<
    [squadId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setHubDao: TypedContractMethod<[_hubDao: AddressLike], [void], "nonpayable">;

  squadCount: TypedContractMethod<[], [bigint], "view">;

  squads: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        squadType: bigint;
        budget: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addMember"
  ): TypedContractMethod<
    [squadId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "assignTask"
  ): TypedContractMethod<
    [squadId: BigNumberish, taskId: BigNumberish, assignee: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [squadId: BigNumberish, taskId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSquad"
  ): TypedContractMethod<
    [name: string, squadType: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [squadId: BigNumberish, description: string, reward: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundSquadBudget"
  ): TypedContractMethod<
    [squadId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getSquadName"
  ): TypedContractMethod<[squadId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "hubDao"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeMember"
  ): TypedContractMethod<
    [squadId: BigNumberish, member: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHubDao"
  ): TypedContractMethod<[_hubDao: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "squadCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "squads"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint] & {
        name: string;
        squadType: bigint;
        budget: bigint;
        taskCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "BudgetAllocated"
  ): TypedContractEvent<
    BudgetAllocatedEvent.InputTuple,
    BudgetAllocatedEvent.OutputTuple,
    BudgetAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "MemberAdded"
  ): TypedContractEvent<
    MemberAddedEvent.InputTuple,
    MemberAddedEvent.OutputTuple,
    MemberAddedEvent.OutputObject
  >;
  getEvent(
    key: "MemberRemoved"
  ): TypedContractEvent<
    MemberRemovedEvent.InputTuple,
    MemberRemovedEvent.OutputTuple,
    MemberRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SquadCreated"
  ): TypedContractEvent<
    SquadCreatedEvent.InputTuple,
    SquadCreatedEvent.OutputTuple,
    SquadCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskAssigned"
  ): TypedContractEvent<
    TaskAssignedEvent.InputTuple,
    TaskAssignedEvent.OutputTuple,
    TaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "BudgetAllocated(uint256,uint256)": TypedContractEvent<
      BudgetAllocatedEvent.InputTuple,
      BudgetAllocatedEvent.OutputTuple,
      BudgetAllocatedEvent.OutputObject
    >;
    BudgetAllocated: TypedContractEvent<
      BudgetAllocatedEvent.InputTuple,
      BudgetAllocatedEvent.OutputTuple,
      BudgetAllocatedEvent.OutputObject
    >;

    "MemberAdded(uint256,address)": TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;
    MemberAdded: TypedContractEvent<
      MemberAddedEvent.InputTuple,
      MemberAddedEvent.OutputTuple,
      MemberAddedEvent.OutputObject
    >;

    "MemberRemoved(uint256,address)": TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;
    MemberRemoved: TypedContractEvent<
      MemberRemovedEvent.InputTuple,
      MemberRemovedEvent.OutputTuple,
      MemberRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SquadCreated(uint256,string,uint8)": TypedContractEvent<
      SquadCreatedEvent.InputTuple,
      SquadCreatedEvent.OutputTuple,
      SquadCreatedEvent.OutputObject
    >;
    SquadCreated: TypedContractEvent<
      SquadCreatedEvent.InputTuple,
      SquadCreatedEvent.OutputTuple,
      SquadCreatedEvent.OutputObject
    >;

    "TaskAssigned(uint256,uint256,address)": TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;
    TaskAssigned: TypedContractEvent<
      TaskAssignedEvent.InputTuple,
      TaskAssignedEvent.OutputTuple,
      TaskAssignedEvent.OutputObject
    >;

    "TaskCompleted(uint256,uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(uint256,uint256,string,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
