/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBuyback,
  IBuybackInterface,
} from "../../../contracts/HubDAO.sol/IBuyback";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdcAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minConsulOut",
        type: "uint256",
      },
    ],
    name: "executeBuyback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBuyback__factory {
  static readonly abi = _abi;
  static createInterface(): IBuybackInterface {
    return new Interface(_abi) as IBuybackInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBuyback {
    return new Contract(address, _abi, runner) as unknown as IBuyback;
  }
}
