/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConsulStaking,
  IConsulStakingInterface,
} from "../../../contracts/HubDAO.sol/IConsulStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getVotingPower",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalStaked",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IConsulStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IConsulStakingInterface {
    return new Interface(_abi) as IConsulStakingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConsulStaking {
    return new Contract(address, _abi, runner) as unknown as IConsulStaking;
  }
}
