/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISquads,
  ISquadsInterface,
} from "../../../contracts/HubDAO.sol/ISquads";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "squadId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "fundSquadBudget",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISquads__factory {
  static readonly abi = _abi;
  static createInterface(): ISquadsInterface {
    return new Interface(_abi) as ISquadsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ISquads {
    return new Contract(address, _abi, runner) as unknown as ISquads;
  }
}
