// Auto-generated by deploy.ts — 2026-02-07T22:57:49.483Z
// Network: baseSepolia
// Deployer: 0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd

import { type Address } from "viem";

export const DEPLOYED_ADDRESSES = {
  consulToken: "0x1d40167E2677dE949d282976EeeBB0eFD918F671" as Address,
  consulStaking: "0xDB980CAd7a45DD6E65b9455942A01F86C4f26aEB" as Address,
  hubDAO: "0x0104f0a251C08804fb8F568EB8FEd48503BAf9D5" as Address,
  buyback: "0x75A606b73DdEba6e08F1a97478e5c2B01Ce4c0a0" as Address,
  fundraiser: "0xA93B4229bAb4E07614D0dB8927322c99b809283c" as Address,
  squads: "0x734133d4fa394Adf362B8959670aaEd82E35f607" as Address,
  projectRegistry: "0x47bD5b0336943e46a10c83400493F70A41C46573" as Address,
  antiRugHook: "0xDF2AC9680AA051059F56a863E8D6719228d71080" as Address,
} as const;

// Infrastructure contracts
export const INFRA_ADDRESSES = {
  hookDeployer: "0x360276E32Cb4f59CCfC03A671F845F50e0bcB65D" as Address,
} as const;

// External contract addresses
export const EXTERNAL_ADDRESSES = {
  usdc: "0x036CbD53842c5426634e7929541eC2318f3dCF7e" as Address,
  poolManager: "0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408" as Address,
} as const;

// Constructor arguments (for verification)
export const CONSTRUCTOR_ARGS = {
  consulToken: ["0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd"],
  consulStaking: ["0x1d40167E2677dE949d282976EeeBB0eFD918F671", "0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd"],
  hubDAO: ["0x036CbD53842c5426634e7929541eC2318f3dCF7e", "0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd"],
  buyback: ["0x036CbD53842c5426634e7929541eC2318f3dCF7e", "0x1d40167E2677dE949d282976EeeBB0eFD918F671", "0x0104f0a251C08804fb8F568EB8FEd48503BAf9D5", "0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd"],
  fundraiser: ["0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd", "0x0104f0a251C08804fb8F568EB8FEd48503BAf9D5", "0x036CbD53842c5426634e7929541eC2318f3dCF7e", "10000000000", "2592000"],
  squads: ["0xF1fa20027b6202bc18e4454149C85CB01dC91Dfd"],
  projectRegistry: [],
  antiRugHook: ["0x05E73354cFDd6745C338b50BcFDfA3Aa6fA03408"],
} as const;
