/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HubDAO__factory } from "./HubDAO__factory";
export { ProjectRegistry__factory } from "./ProjectRegistry__factory";
