/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface HubDAOInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_VOTING_THRESHOLD"
      | "allocateSquadBudget"
      | "approveBudget"
      | "buybackContract"
      | "currentQuarter"
      | "executeBudget"
      | "getTreasuryBalance"
      | "getVotingPower"
      | "owner"
      | "proposeBudget"
      | "quarterlyBudgets"
      | "renounceOwnership"
      | "setBuybackContract"
      | "setSquadsContract"
      | "setStakingContract"
      | "setVetoPower"
      | "squadsContract"
      | "stakingContract"
      | "transferOwnership"
      | "treasuryToken"
      | "triggerBuyback"
      | "vetoBudget"
      | "vetoPowerHolders"
      | "voteOnBudget"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetApproved"
      | "BudgetExecuted"
      | "BudgetProposed"
      | "BudgetVoted"
      | "OwnershipTransferred"
      | "VetoExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_VOTING_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateSquadBudget",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "buybackContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentQuarter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBudget",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quarterlyBudgets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBuybackContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSquadsContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVetoPower",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "squadsContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerBuyback",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vetoBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vetoPowerHolders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOnBudget",
    values: [BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_VOTING_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateSquadBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buybackContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentQuarter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeBudget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quarterlyBudgets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBuybackContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSquadsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVetoPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "squadsContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerBuyback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vetoBudget", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vetoPowerHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteOnBudget",
    data: BytesLike
  ): Result;
}

export namespace BudgetApprovedEvent {
  export type InputTuple = [quarter: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [quarter: bigint, amount: bigint];
  export interface OutputObject {
    quarter: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetExecutedEvent {
  export type InputTuple = [
    quarter: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    quarter: bigint,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    quarter: bigint;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetProposedEvent {
  export type InputTuple = [quarter: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [quarter: bigint, amount: bigint];
  export interface OutputObject {
    quarter: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BudgetVotedEvent {
  export type InputTuple = [
    quarter: BigNumberish,
    voter: AddressLike,
    support: boolean
  ];
  export type OutputTuple = [quarter: bigint, voter: string, support: boolean];
  export interface OutputObject {
    quarter: bigint;
    voter: string;
    support: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VetoExecutedEvent {
  export type InputTuple = [quarter: BigNumberish, vetoer: AddressLike];
  export type OutputTuple = [quarter: bigint, vetoer: string];
  export interface OutputObject {
    quarter: bigint;
    vetoer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HubDAO extends BaseContract {
  connect(runner?: ContractRunner | null): HubDAO;
  waitForDeployment(): Promise<this>;

  interface: HubDAOInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_VOTING_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  allocateSquadBudget: TypedContractMethod<
    [quarter: BigNumberish, squadId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveBudget: TypedContractMethod<
    [quarter: BigNumberish],
    [void],
    "nonpayable"
  >;

  buybackContract: TypedContractMethod<[], [string], "view">;

  currentQuarter: TypedContractMethod<[], [bigint], "view">;

  executeBudget: TypedContractMethod<
    [quarter: BigNumberish, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTreasuryBalance: TypedContractMethod<[], [bigint], "view">;

  getVotingPower: TypedContractMethod<[voter: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposeBudget: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  quarterlyBudgets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        amount: bigint;
        spent: bigint;
        startTime: bigint;
        endTime: bigint;
        approved: boolean;
        totalVotePower: bigint;
        snapshotTotalStaked: bigint;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBuybackContract: TypedContractMethod<
    [_buybackContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setSquadsContract: TypedContractMethod<
    [_squadsContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setStakingContract: TypedContractMethod<
    [_stakingContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setVetoPower: TypedContractMethod<
    [holder: AddressLike, hasPower: boolean],
    [void],
    "nonpayable"
  >;

  squadsContract: TypedContractMethod<[], [string], "view">;

  stakingContract: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasuryToken: TypedContractMethod<[], [string], "view">;

  triggerBuyback: TypedContractMethod<
    [
      quarter: BigNumberish,
      usdcAmount: BigNumberish,
      minConsulOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  vetoBudget: TypedContractMethod<
    [quarter: BigNumberish],
    [void],
    "nonpayable"
  >;

  vetoPowerHolders: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  voteOnBudget: TypedContractMethod<
    [quarter: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_VOTING_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allocateSquadBudget"
  ): TypedContractMethod<
    [quarter: BigNumberish, squadId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "approveBudget"
  ): TypedContractMethod<[quarter: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "buybackContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentQuarter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeBudget"
  ): TypedContractMethod<
    [quarter: BigNumberish, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTreasuryBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVotingPower"
  ): TypedContractMethod<[voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeBudget"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "quarterlyBudgets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        amount: bigint;
        spent: bigint;
        startTime: bigint;
        endTime: bigint;
        approved: boolean;
        totalVotePower: bigint;
        snapshotTotalStaked: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBuybackContract"
  ): TypedContractMethod<[_buybackContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSquadsContract"
  ): TypedContractMethod<[_squadsContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingContract"
  ): TypedContractMethod<[_stakingContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVetoPower"
  ): TypedContractMethod<
    [holder: AddressLike, hasPower: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "squadsContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasuryToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerBuyback"
  ): TypedContractMethod<
    [
      quarter: BigNumberish,
      usdcAmount: BigNumberish,
      minConsulOut: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vetoBudget"
  ): TypedContractMethod<[quarter: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vetoPowerHolders"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "voteOnBudget"
  ): TypedContractMethod<
    [quarter: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BudgetApproved"
  ): TypedContractEvent<
    BudgetApprovedEvent.InputTuple,
    BudgetApprovedEvent.OutputTuple,
    BudgetApprovedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetExecuted"
  ): TypedContractEvent<
    BudgetExecutedEvent.InputTuple,
    BudgetExecutedEvent.OutputTuple,
    BudgetExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetProposed"
  ): TypedContractEvent<
    BudgetProposedEvent.InputTuple,
    BudgetProposedEvent.OutputTuple,
    BudgetProposedEvent.OutputObject
  >;
  getEvent(
    key: "BudgetVoted"
  ): TypedContractEvent<
    BudgetVotedEvent.InputTuple,
    BudgetVotedEvent.OutputTuple,
    BudgetVotedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VetoExecuted"
  ): TypedContractEvent<
    VetoExecutedEvent.InputTuple,
    VetoExecutedEvent.OutputTuple,
    VetoExecutedEvent.OutputObject
  >;

  filters: {
    "BudgetApproved(uint256,uint256)": TypedContractEvent<
      BudgetApprovedEvent.InputTuple,
      BudgetApprovedEvent.OutputTuple,
      BudgetApprovedEvent.OutputObject
    >;
    BudgetApproved: TypedContractEvent<
      BudgetApprovedEvent.InputTuple,
      BudgetApprovedEvent.OutputTuple,
      BudgetApprovedEvent.OutputObject
    >;

    "BudgetExecuted(uint256,address,uint256)": TypedContractEvent<
      BudgetExecutedEvent.InputTuple,
      BudgetExecutedEvent.OutputTuple,
      BudgetExecutedEvent.OutputObject
    >;
    BudgetExecuted: TypedContractEvent<
      BudgetExecutedEvent.InputTuple,
      BudgetExecutedEvent.OutputTuple,
      BudgetExecutedEvent.OutputObject
    >;

    "BudgetProposed(uint256,uint256)": TypedContractEvent<
      BudgetProposedEvent.InputTuple,
      BudgetProposedEvent.OutputTuple,
      BudgetProposedEvent.OutputObject
    >;
    BudgetProposed: TypedContractEvent<
      BudgetProposedEvent.InputTuple,
      BudgetProposedEvent.OutputTuple,
      BudgetProposedEvent.OutputObject
    >;

    "BudgetVoted(uint256,address,bool)": TypedContractEvent<
      BudgetVotedEvent.InputTuple,
      BudgetVotedEvent.OutputTuple,
      BudgetVotedEvent.OutputObject
    >;
    BudgetVoted: TypedContractEvent<
      BudgetVotedEvent.InputTuple,
      BudgetVotedEvent.OutputTuple,
      BudgetVotedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VetoExecuted(uint256,address)": TypedContractEvent<
      VetoExecutedEvent.InputTuple,
      VetoExecutedEvent.OutputTuple,
      VetoExecutedEvent.OutputObject
    >;
    VetoExecuted: TypedContractEvent<
      VetoExecutedEvent.InputTuple,
      VetoExecutedEvent.OutputTuple,
      VetoExecutedEvent.OutputObject
    >;
  };
}
